### ISSUE TITLE
Coinbase widget displaying

### ISSUE THREAD

**Issue by jmreicha** [coinbase/coinbase-wordpress#12]
I have followed the instructions given in the README for setting up the donation button but the widget is not rendering properly in the sidebar of my site.  The only thing that is showing up correctly is title of the widget, nothing else.  Wordpress version is 3.9.2.

Here is the error when I paste the short code in to a page:

`There was an error connecting to Coinbase: Status code 401. Please check your internet connection and API credentials.`

Are there other settings that I should be aware of or that I need to check?

**Comment by brandedux** [comment]
How did you "activate" it?

**Comment by C0deZLee** [comment]
How do you activate it? Searched the whole internet and seems like no one has a clue @MBSystems

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
