### ISSUE TITLE
Add option to collect email address from customer

### ISSUE THREAD

**Issue by ghost** [coinbase/coinbase-wordpress#14]
It would be useful if we could include a checkbox in the admin panel "collect email address". If selected, the payment form would show a text input to collect an email address from the customer.

Currently, an email address can be passed on the 'custom' parameter, however this requires coding by WordPress users to collect the email address in their own input and pass this into the widget when instantiating it. If we made this an option, we could make it very easy for WordPress users to collect an email address when needed.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
