### ISSUE TITLE
Installing give a fatal error

### ISSUE THREAD

**Issue by andreamarucci** [coinbase/coinbase-wordpress#15]
Just installed the plugin on WP 4.9.4 and tried to activating it give me this error

Warning: require_once(/home/xxx/public_html/sito/wp-content/plugins/coinbase-wordpress-master/coinbase-php/lib/Coinbase.php): failed to open stream: No such file or directory in /home/xxx/public_html/sito/wp-content/plugins/coinbase-wordpress-master/coinbase.php on line 35

So it's not possible to activate the plugin.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
